version: '2.12.2'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db-data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: dkphobos/foodgram:latest
    restart: always
    volumes:
      - backend_static_value:/app/static/
      - backend_media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env 

  frontend:
    image: dkphobos/frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - backend_static_value:/var/html/backend_static/
      - backend_media_value:/var/html/backend_media/
    depends_on:
      - frontend

volumes:
  db-data:
  backend_static_value:
  backend_media_value:
